name: Build and publish
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/open-platforms-org/ministack-ui-frontend:latest
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/open-platforms-org/ministack-ui-backend:latest
      # Publish to Docker Hub as well
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ministack-ui-frontend:latest

      - name: Build and push backend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ministack-ui-backend:latest
